baseurl = "http://localhost"
title = "Greg Boggs"
uglyurls = false
paginate = 10

[permalinks]
  post = "/:title"

[params]
  Author = "Greg Boggs"
  DateForm = "Jan 2, 2006"
  googleAnalytics = "UA-xxxxxxx-x"
  jquery = "2.1.4"
  SyntaxHighlightTheme = "solarized_dark.min.css"
  
  #Starter theme specifics
  tagline = "Portland Drupal Developer"
  intro = "I make websites that <strong>succeed.</strong>"
  github = "https://github.com/Greg-Boggs/"
  linkedin = "https://www.linkedin.com/in/gregoryboggs"
  twitter = "https://twitter.com/gregory_boggs"

[Indexes]
  categories = "categories"

[[menu.top]]
    name = "Blog"
    url = "/blog/"
    
[[menu.blog]]
    name = "Scan WP"
    url = "http://www.scanwp.com"
[[menu.blog]]
    name = "CSS Complexity"
    url = "http://css.gregboggs.com"
[[menu.blog]]
    name = "Hugo Starter Theme"
    url = "https://github.com/Greg-Boggs/starter"
[[menu.blog]]
    name = "Wesnoth Gaming Ladder"
    url = "http://sourceforge.net/projects/gamingladder/"